[features]
seeds = false
skip-lint = false

[programs.devnet]
taskaru_solang = "8cTeqUjgcLhLhD6nzVoioJ8sbDnitsz86TtFSNjyrVnr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/purrnama/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
